name: Deploy to Render

on:
  push:
    branches:
      - main 

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
